server:
  port: 40000
eureka:
  instance:
    hostname: ${spring.application.name}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:20000/eureka/